version: '3.8'

services:
  op-node:
    image: ghcr.io/openvino/op-node.base-sepolia:latest
    container_name: op-node.base-sepolia
    restart: always
    ports:
      - "9545:9545"     # L2 RPC
      - "9003:9003"     # Prometheus metrics
    volumes:
      - ./rollup.json:/data/rollup.json
      - ./entrypoint.sh:/entrypoint.sh:ro
      - opnode_data:/data
      - docker-base-sepolia_jwt_shared:/jwt:rw
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  opnode_data:
  docker-base-sepolia_jwt_shared:

networks:
  default:
    external:
      name: base-sepolia-test

