version: '3.8'

services:
  op-node:
    build: .
    image: ghcr.io/openvino/op-node.base-sepolia:latest
    container_name: op-node.base-sepolia
    restart: always
    ports:
      - "9545:9545"     # L2 RPC
      - "9003:9003"     # Prometheus metrics
    volumes:
      - ./rollup.json:/data/rollup.json
      - opnode_data:/data
      - docker-base-sepolia_jwt_shared:/jwt:ro
    env_file:
      - .env
    command:
      [
        "op-node",
        "--l1", "$OP_NODE_L1_RPC",
        "--l2", "$OP_NODE_L2_RPC",
        "--l1.beacon", "$OP_NODE_L1_BEACON",
        "--l1.auth", "$OP_NODE_L1_AUTH",
        "--l1.jwt-secret", "$OP_NODE_JWT_SECRET",
        "--rollup.config", "$OP_NODE_ROLLUP_CONFIG",
        "--rpc.addr", "0.0.0.0",
        "--rpc.port", "9545",
        "--metrics.enabled",
        "--metrics.addr", "0.0.0.0",
        "--metrics.port", "9003",
        "--p2p.disable",
        "--network", "base-sepolia"
      ]

volumes:
  opnode_data:
  docker-base-sepolia_jwt_shared:

networks:
  default:
    external:
      name: base-sepolia-test

