version: '3.8'
services:
  op-node:
    build: .
    image: opnode.base-sepolia.dnp.dappnode.eth
    container_name: op-node.base-sepolia
    restart: always
    ports:
      - "9545:9545"
      - "9003:9003"
    volumes:
      - opnode_data:/data
    environment:
      - OP_NODE_L1_RPC=https://sepolia.infura.io/v3/YOUR_KEY
      - OP_NODE_L2_RPC=http://geth:8545
      - OP_NODE_ROLLUP_CONFIG=/data/rollup.json
    command:
      [
        "op-node",
        "--l1",
        "$OP_NODE_L1_RPC",
        "--l2",
        "$OP_NODE_L2_RPC",
        "--rollup.config",
        "$OP_NODE_ROLLUP_CONFIG",
        "--rpc.addr",
        "0.0.0.0",
        "--rpc.port",
        "9545",
        "--metrics.enabled",
        "--metrics.addr",
        "0.0.0.0",
        "--metrics.port",
        "9003"
      ]

volumes:
  opnode_data:

